apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello
  name: hello-nodeport
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 31000
  selector:
    app: hello
  type: NodePort
